[workspace]
members = [".", "libs/state", "libs/utils", "libs/oauth2"]

[package]
name = "rustdesk-api"
version = "3.0.1"
edition = "2021"
build = "build.rs"

[features]
coverage = []

[dependencies]
getrandom = "0.2"
signal-hook = "0.3"
log = "0.4"
include_dir = "0.7"
tokio = { version = "1", features = ["full"] }
rocket = { version = "0.5", features = ["json", "secrets"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "macros",
    "chrono",
    "json",
] }
reqwest = { version = "0.12", default-features = false, features = ["json","rustls-tls-native-roots"] }
rocket_okapi = { version = "0.8", features = [ "swagger" ]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
state = { path = "libs/state" }
utils = { path = "libs/utils" }
oauth2 = { path = "libs/oauth2" }
uuid = { version = "1.10", features = ["v4"] }
base64 = "0.22"
url = { version = "2", features = ["serde"] }
urlencoding = "2.1"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
state = { path = "libs/state", features = ["test-util"] }

[build-dependencies]
serde_json = "1.0"