/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AuditAlarmRequest } from '../models';
import { AuditConnRequest } from '../models';
import { AuditFileRequest } from '../models';
import { AuditRequest } from '../models';
/**
 * AuditApi - axios parameter creator
 * @export
 */
export const AuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Audit (legacy endpoint, delegates to conn handler)
         * @param {AuditRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        audit: async (body: AuditRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling audit.');
            }
            const localVarPath = `/api/audit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Audit alarm events
         * @param {AuditAlarmRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditAlarm: async (body: AuditAlarmRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auditAlarm.');
            }
            const localVarPath = `/api/audit/alarm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Audit connection events
         * @param {AuditConnRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditConn: async (body: AuditConnRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auditConn.');
            }
            const localVarPath = `/api/audit/conn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Query active audit connection
         * @param {string} id 
         * @param {string} session_id 
         * @param {string} conn_type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditConnActive: async (id: string, session_id: string, conn_type: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling auditConnActive.');
            }
            // verify required parameter 'session_id' is not null or undefined
            if (session_id === null || session_id === undefined) {
                throw new RequiredError('session_id','Required parameter session_id was null or undefined when calling auditConnActive.');
            }
            // verify required parameter 'conn_type' is not null or undefined
            if (conn_type === null || conn_type === undefined) {
                throw new RequiredError('conn_type','Required parameter conn_type was null or undefined when calling auditConnActive.');
            }
            const localVarPath = `/api/audit/conn/active`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (session_id !== undefined) {
                localVarQueryParameter['session_id'] = session_id;
            }

            if (conn_type !== undefined) {
                localVarQueryParameter['conn_type'] = conn_type;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Audit file transfer events
         * @param {AuditFileRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditFile: async (body: AuditFileRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auditFile.');
            }
            const localVarPath = `/api/audit/file`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditApi - functional programming interface
 * @export
 */
export const AuditApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Audit (legacy endpoint, delegates to conn handler)
         * @param {AuditRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audit(body: AuditRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).audit(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Audit alarm events
         * @param {AuditAlarmRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditAlarm(body: AuditAlarmRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditAlarm(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Audit connection events
         * @param {AuditConnRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConn(body: AuditConnRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditConn(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Query active audit connection
         * @param {string} id 
         * @param {string} session_id 
         * @param {string} conn_type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConnActive(id: string, session_id: string, conn_type: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditConnActive(id, session_id, conn_type, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Audit file transfer events
         * @param {AuditFileRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditFile(body: AuditFileRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditFile(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AuditApi - factory interface
 * @export
 */
export const AuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Audit (legacy endpoint, delegates to conn handler)
         * @param {AuditRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audit(body: AuditRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return AuditApiFp(configuration).audit(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Audit alarm events
         * @param {AuditAlarmRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditAlarm(body: AuditAlarmRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return AuditApiFp(configuration).auditAlarm(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Audit connection events
         * @param {AuditConnRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConn(body: AuditConnRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return AuditApiFp(configuration).auditConn(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Query active audit connection
         * @param {string} id 
         * @param {string} session_id 
         * @param {string} conn_type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConnActive(id: string, session_id: string, conn_type: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return AuditApiFp(configuration).auditConnActive(id, session_id, conn_type, options).then((request) => request(axios, basePath));
        },
        /**
         * Audit file transfer events
         * @param {AuditFileRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditFile(body: AuditFileRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return AuditApiFp(configuration).auditFile(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditApi - object-oriented interface
 * @export
 * @class AuditApi
 * @extends {BaseAPI}
 */
export class AuditApi extends BaseAPI {
    /**
     * Audit (legacy endpoint, delegates to conn handler)
     * @param {AuditRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async audit(body: AuditRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return AuditApiFp(this.configuration).audit(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Audit alarm events
     * @param {AuditAlarmRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditAlarm(body: AuditAlarmRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return AuditApiFp(this.configuration).auditAlarm(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Audit connection events
     * @param {AuditConnRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditConn(body: AuditConnRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return AuditApiFp(this.configuration).auditConn(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Query active audit connection
     * @param {string} id 
     * @param {string} session_id 
     * @param {string} conn_type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditConnActive(id: string, session_id: string, conn_type: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return AuditApiFp(this.configuration).auditConnActive(id, session_id, conn_type, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Audit file transfer events
     * @param {AuditFileRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditFile(body: AuditFileRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return AuditApiFp(this.configuration).auditFile(body, options).then((request) => request(this.axios, this.basePath));
    }
}
