/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AuditAlarmRequest } from '../models';
import { AuditConnRequest } from '../models';
import { AuditFileRequest } from '../models';
import { AuditNoteRequest } from '../models';
import { AuditPageForAuditAlarmLog } from '../models';
import { AuditPageForAuditConnLog } from '../models';
import { AuditPageForAuditConsoleLog } from '../models';
import { AuditPageForAuditFileLog } from '../models';
import { AuditRefResponse } from '../models';
import { AuditRequest } from '../models';
/**
 * AuditApi - axios parameter creator
 * @export
 */
export const AuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Audit (legacy endpoint, delegates to conn handler)
         * @param {AuditRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        audit: async (body: AuditRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling audit.');
            }
            const localVarPath = `/api/audit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Audit alarm events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditAlarmRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditAlarm: async (body: AuditAlarmRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auditAlarm.');
            }
            const localVarPath = `/api/audit/alarm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Audit connection events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditConnRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditConn: async (body: AuditConnRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auditConn.');
            }
            const localVarPath = `/api/audit/conn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Query active audit connection
         * @param {string} id 
         * @param {string} session_id 
         * @param {string} conn_type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditConnActive: async (id: string, session_id: string, conn_type: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling auditConnActive.');
            }
            // verify required parameter 'session_id' is not null or undefined
            if (session_id === null || session_id === undefined) {
                throw new RequiredError('session_id','Required parameter session_id was null or undefined when calling auditConnActive.');
            }
            // verify required parameter 'conn_type' is not null or undefined
            if (conn_type === null || conn_type === undefined) {
                throw new RequiredError('conn_type','Required parameter conn_type was null or undefined when calling auditConnActive.');
            }
            const localVarPath = `/api/audit/conn/active`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            if (session_id !== undefined) {
                localVarQueryParameter['session_id'] = session_id;
            }

            if (conn_type !== undefined) {
                localVarQueryParameter['conn_type'] = conn_type;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Audit file transfer events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditFileRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditFile: async (body: AuditFileRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auditFile.');
            }
            const localVarPath = `/api/audit/file`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Spec §8: the viewer's note for the connection `guid` came from `GET /api/audit/conn/active`.
         * @summary Set an end-of-session note
         * @param {AuditNoteRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditNote: async (body: AuditNoteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auditNote.');
            }
            const localVarPath = `/api/audit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Called by hbbs with the viewer's token (audit-api-spec §11). The ref names the caller only, so any logged-in user may mint one.
         * @summary Mint a connection audit ref
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditRef: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/audit/ref`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Pro-compatible (`audits.py alarm`): newest first; `device` is an SQL LIKE pattern.
         * @summary Security alarm audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [device] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditsAlarm: async (current?: number, page_size?: number, created_at?: string, device?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/audits/alarm`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (current !== undefined) {
                localVarQueryParameter['current'] = current;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (created_at !== undefined) {
                localVarQueryParameter['created_at'] = created_at;
            }

            if (device !== undefined) {
                localVarQueryParameter['device'] = device;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Pro-compatible (`audits.py conn`): newest first; `remote` is an SQL LIKE pattern.
         * @summary Connection audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [remote] 
         * @param {number} [conn_type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditsConn: async (current?: number, page_size?: number, created_at?: string, remote?: string, conn_type?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/audits/conn`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (current !== undefined) {
                localVarQueryParameter['current'] = current;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (created_at !== undefined) {
                localVarQueryParameter['created_at'] = created_at;
            }

            if (remote !== undefined) {
                localVarQueryParameter['remote'] = remote;
            }

            if (conn_type !== undefined) {
                localVarQueryParameter['conn_type'] = conn_type;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Pro-compatible (`audits.py console`): nothing writes `audit_console` yet, so this always answers an empty page (audit-api-spec.md §9, §14).
         * @summary Console audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [operator] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditsConsole: async (current?: number, page_size?: number, created_at?: string, operator?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/audits/console`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (current !== undefined) {
                localVarQueryParameter['current'] = current;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (created_at !== undefined) {
                localVarQueryParameter['created_at'] = created_at;
            }

            if (operator !== undefined) {
                localVarQueryParameter['operator'] = operator;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Pro-compatible (`audits.py file`): newest first; `remote` is an SQL LIKE pattern.
         * @summary File transfer audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [remote] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auditsFile: async (current?: number, page_size?: number, created_at?: string, remote?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/audits/file`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (current !== undefined) {
                localVarQueryParameter['current'] = current;
            }

            if (page_size !== undefined) {
                localVarQueryParameter['pageSize'] = page_size;
            }

            if (created_at !== undefined) {
                localVarQueryParameter['created_at'] = created_at;
            }

            if (remote !== undefined) {
                localVarQueryParameter['remote'] = remote;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditApi - functional programming interface
 * @export
 */
export const AuditApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Audit (legacy endpoint, delegates to conn handler)
         * @param {AuditRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audit(body: AuditRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).audit(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Audit alarm events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditAlarmRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditAlarm(body: AuditAlarmRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditAlarm(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Audit connection events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditConnRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConn(body: AuditConnRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditConn(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Query active audit connection
         * @param {string} id 
         * @param {string} session_id 
         * @param {string} conn_type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConnActive(id: string, session_id: string, conn_type: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditConnActive(id, session_id, conn_type, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Audit file transfer events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditFileRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditFile(body: AuditFileRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditFile(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Spec §8: the viewer's note for the connection `guid` came from `GET /api/audit/conn/active`.
         * @summary Set an end-of-session note
         * @param {AuditNoteRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditNote(body: AuditNoteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditNote(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Called by hbbs with the viewer's token (audit-api-spec §11). The ref names the caller only, so any logged-in user may mint one.
         * @summary Mint a connection audit ref
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditRef(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AuditRefResponse>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditRef(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Pro-compatible (`audits.py alarm`): newest first; `device` is an SQL LIKE pattern.
         * @summary Security alarm audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [device] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsAlarm(current?: number, page_size?: number, created_at?: string, device?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AuditPageForAuditAlarmLog>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditsAlarm(current, page_size, created_at, device, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Pro-compatible (`audits.py conn`): newest first; `remote` is an SQL LIKE pattern.
         * @summary Connection audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [remote] 
         * @param {number} [conn_type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsConn(current?: number, page_size?: number, created_at?: string, remote?: string, conn_type?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AuditPageForAuditConnLog>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditsConn(current, page_size, created_at, remote, conn_type, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Pro-compatible (`audits.py console`): nothing writes `audit_console` yet, so this always answers an empty page (audit-api-spec.md §9, §14).
         * @summary Console audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [operator] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsConsole(current?: number, page_size?: number, created_at?: string, operator?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AuditPageForAuditConsoleLog>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditsConsole(current, page_size, created_at, operator, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Pro-compatible (`audits.py file`): newest first; `remote` is an SQL LIKE pattern.
         * @summary File transfer audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [remote] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsFile(current?: number, page_size?: number, created_at?: string, remote?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AuditPageForAuditFileLog>>> {
            const localVarAxiosArgs = await AuditApiAxiosParamCreator(configuration).auditsFile(current, page_size, created_at, remote, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AuditApi - factory interface
 * @export
 */
export const AuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Audit (legacy endpoint, delegates to conn handler)
         * @param {AuditRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audit(body: AuditRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return AuditApiFp(configuration).audit(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Audit alarm events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditAlarmRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditAlarm(body: AuditAlarmRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return AuditApiFp(configuration).auditAlarm(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Audit connection events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditConnRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConn(body: AuditConnRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return AuditApiFp(configuration).auditConn(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Query active audit connection
         * @param {string} id 
         * @param {string} session_id 
         * @param {string} conn_type 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditConnActive(id: string, session_id: string, conn_type: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return AuditApiFp(configuration).auditConnActive(id, session_id, conn_type, options).then((request) => request(axios, basePath));
        },
        /**
         * Audit file transfer events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
         * @param {AuditFileRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditFile(body: AuditFileRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return AuditApiFp(configuration).auditFile(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Spec §8: the viewer's note for the connection `guid` came from `GET /api/audit/conn/active`.
         * @summary Set an end-of-session note
         * @param {AuditNoteRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditNote(body: AuditNoteRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return AuditApiFp(configuration).auditNote(body, options).then((request) => request(axios, basePath));
        },
        /**
         * Called by hbbs with the viewer's token (audit-api-spec §11). The ref names the caller only, so any logged-in user may mint one.
         * @summary Mint a connection audit ref
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditRef(options?: AxiosRequestConfig): Promise<AxiosResponse<AuditRefResponse>> {
            return AuditApiFp(configuration).auditRef(options).then((request) => request(axios, basePath));
        },
        /**
         * Pro-compatible (`audits.py alarm`): newest first; `device` is an SQL LIKE pattern.
         * @summary Security alarm audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [device] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsAlarm(current?: number, page_size?: number, created_at?: string, device?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AuditPageForAuditAlarmLog>> {
            return AuditApiFp(configuration).auditsAlarm(current, page_size, created_at, device, options).then((request) => request(axios, basePath));
        },
        /**
         * Pro-compatible (`audits.py conn`): newest first; `remote` is an SQL LIKE pattern.
         * @summary Connection audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [remote] 
         * @param {number} [conn_type] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsConn(current?: number, page_size?: number, created_at?: string, remote?: string, conn_type?: number, options?: AxiosRequestConfig): Promise<AxiosResponse<AuditPageForAuditConnLog>> {
            return AuditApiFp(configuration).auditsConn(current, page_size, created_at, remote, conn_type, options).then((request) => request(axios, basePath));
        },
        /**
         * Pro-compatible (`audits.py console`): nothing writes `audit_console` yet, so this always answers an empty page (audit-api-spec.md §9, §14).
         * @summary Console audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [operator] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsConsole(current?: number, page_size?: number, created_at?: string, operator?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AuditPageForAuditConsoleLog>> {
            return AuditApiFp(configuration).auditsConsole(current, page_size, created_at, operator, options).then((request) => request(axios, basePath));
        },
        /**
         * Pro-compatible (`audits.py file`): newest first; `remote` is an SQL LIKE pattern.
         * @summary File transfer audit log
         * @param {number} [current] 
         * @param {number} [page_size] 
         * @param {string} [created_at] 
         * @param {string} [remote] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async auditsFile(current?: number, page_size?: number, created_at?: string, remote?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<AuditPageForAuditFileLog>> {
            return AuditApiFp(configuration).auditsFile(current, page_size, created_at, remote, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditApi - object-oriented interface
 * @export
 * @class AuditApi
 * @extends {BaseAPI}
 */
export class AuditApi extends BaseAPI {
    /**
     * Audit (legacy endpoint, delegates to conn handler)
     * @param {AuditRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async audit(body: AuditRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return AuditApiFp(this.configuration).audit(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Audit alarm events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
     * @param {AuditAlarmRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditAlarm(body: AuditAlarmRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return AuditApiFp(this.configuration).auditAlarm(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Audit connection events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
     * @param {AuditConnRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditConn(body: AuditConnRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return AuditApiFp(this.configuration).auditConn(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Query active audit connection
     * @param {string} id 
     * @param {string} session_id 
     * @param {string} conn_type 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditConnActive(id: string, session_id: string, conn_type: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return AuditApiFp(this.configuration).auditConnActive(id, session_id, conn_type, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Audit file transfer events  Answers an empty body once the record is stored and `{\"error\": ...}` otherwise; the client retries on any non-empty body (docs/audit-api-spec.md §2.3).
     * @param {AuditFileRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditFile(body: AuditFileRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return AuditApiFp(this.configuration).auditFile(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Spec §8: the viewer's note for the connection `guid` came from `GET /api/audit/conn/active`.
     * @summary Set an end-of-session note
     * @param {AuditNoteRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditNote(body: AuditNoteRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return AuditApiFp(this.configuration).auditNote(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Called by hbbs with the viewer's token (audit-api-spec §11). The ref names the caller only, so any logged-in user may mint one.
     * @summary Mint a connection audit ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditRef(options?: AxiosRequestConfig) : Promise<AxiosResponse<AuditRefResponse>> {
        return AuditApiFp(this.configuration).auditRef(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Pro-compatible (`audits.py alarm`): newest first; `device` is an SQL LIKE pattern.
     * @summary Security alarm audit log
     * @param {number} [current] 
     * @param {number} [page_size] 
     * @param {string} [created_at] 
     * @param {string} [device] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditsAlarm(current?: number, page_size?: number, created_at?: string, device?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AuditPageForAuditAlarmLog>> {
        return AuditApiFp(this.configuration).auditsAlarm(current, page_size, created_at, device, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Pro-compatible (`audits.py conn`): newest first; `remote` is an SQL LIKE pattern.
     * @summary Connection audit log
     * @param {number} [current] 
     * @param {number} [page_size] 
     * @param {string} [created_at] 
     * @param {string} [remote] 
     * @param {number} [conn_type] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditsConn(current?: number, page_size?: number, created_at?: string, remote?: string, conn_type?: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<AuditPageForAuditConnLog>> {
        return AuditApiFp(this.configuration).auditsConn(current, page_size, created_at, remote, conn_type, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Pro-compatible (`audits.py console`): nothing writes `audit_console` yet, so this always answers an empty page (audit-api-spec.md §9, §14).
     * @summary Console audit log
     * @param {number} [current] 
     * @param {number} [page_size] 
     * @param {string} [created_at] 
     * @param {string} [operator] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditsConsole(current?: number, page_size?: number, created_at?: string, operator?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AuditPageForAuditConsoleLog>> {
        return AuditApiFp(this.configuration).auditsConsole(current, page_size, created_at, operator, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Pro-compatible (`audits.py file`): newest first; `remote` is an SQL LIKE pattern.
     * @summary File transfer audit log
     * @param {number} [current] 
     * @param {number} [page_size] 
     * @param {string} [created_at] 
     * @param {string} [remote] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuditApi
     */
    public async auditsFile(current?: number, page_size?: number, created_at?: string, remote?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<AuditPageForAuditFileLog>> {
        return AuditApiFp(this.configuration).auditsFile(current, page_size, created_at, remote, options).then((request) => request(this.axios, this.basePath));
    }
}
