/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { SoftwareVersionResponse } from '../models';
/**
 * SoftwareApi - axios parameter creator
 * @export
 */
export const SoftwareApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This function is an API endpoint that redirects to the software download page.
         * @summary Redirect to the software download page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        softwareDownload: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/software/download`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This function is an API endpoint that simulates the GitHub API for releases.  ## Parameters  - `version`: The version of the release.  ## Returns  Returns a `Json<SoftwareVersionResponse>` object containing the version of the release.
         * @summary Simulate GitHub API for releases
         * @param {string} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        softwareReleasesTag: async (version: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'version' is not null or undefined
            if (version === null || version === undefined) {
                throw new RequiredError('version','Required parameter version was null or undefined when calling softwareReleasesTag.');
            }
            const localVarPath = `/api/software/releases/tag/{version}`
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * This function is an API endpoint that retrieves the version of the server. It is tagged with \"software\" for OpenAPI documentation.  ## Returns  If successful, this function returns a `Json<SoftwareVersionResponse>` object containing the version of the server.
         * @summary Retrieve the server version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        softwareVersion: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/software/version/server`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SoftwareApi - functional programming interface
 * @export
 */
export const SoftwareApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This function is an API endpoint that redirects to the software download page.
         * @summary Redirect to the software download page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async softwareDownload(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await SoftwareApiAxiosParamCreator(configuration).softwareDownload(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This function is an API endpoint that simulates the GitHub API for releases.  ## Parameters  - `version`: The version of the release.  ## Returns  Returns a `Json<SoftwareVersionResponse>` object containing the version of the release.
         * @summary Simulate GitHub API for releases
         * @param {string} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async softwareReleasesTag(version: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SoftwareVersionResponse>>> {
            const localVarAxiosArgs = await SoftwareApiAxiosParamCreator(configuration).softwareReleasesTag(version, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * This function is an API endpoint that retrieves the version of the server. It is tagged with \"software\" for OpenAPI documentation.  ## Returns  If successful, this function returns a `Json<SoftwareVersionResponse>` object containing the version of the server.
         * @summary Retrieve the server version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async softwareVersion(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SoftwareVersionResponse>>> {
            const localVarAxiosArgs = await SoftwareApiAxiosParamCreator(configuration).softwareVersion(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SoftwareApi - factory interface
 * @export
 */
export const SoftwareApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This function is an API endpoint that redirects to the software download page.
         * @summary Redirect to the software download page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async softwareDownload(options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return SoftwareApiFp(configuration).softwareDownload(options).then((request) => request(axios, basePath));
        },
        /**
         * This function is an API endpoint that simulates the GitHub API for releases.  ## Parameters  - `version`: The version of the release.  ## Returns  Returns a `Json<SoftwareVersionResponse>` object containing the version of the release.
         * @summary Simulate GitHub API for releases
         * @param {string} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async softwareReleasesTag(version: string, options?: AxiosRequestConfig): Promise<AxiosResponse<SoftwareVersionResponse>> {
            return SoftwareApiFp(configuration).softwareReleasesTag(version, options).then((request) => request(axios, basePath));
        },
        /**
         * This function is an API endpoint that retrieves the version of the server. It is tagged with \"software\" for OpenAPI documentation.  ## Returns  If successful, this function returns a `Json<SoftwareVersionResponse>` object containing the version of the server.
         * @summary Retrieve the server version
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async softwareVersion(options?: AxiosRequestConfig): Promise<AxiosResponse<SoftwareVersionResponse>> {
            return SoftwareApiFp(configuration).softwareVersion(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SoftwareApi - object-oriented interface
 * @export
 * @class SoftwareApi
 * @extends {BaseAPI}
 */
export class SoftwareApi extends BaseAPI {
    /**
     * This function is an API endpoint that redirects to the software download page.
     * @summary Redirect to the software download page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public async softwareDownload(options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return SoftwareApiFp(this.configuration).softwareDownload(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This function is an API endpoint that simulates the GitHub API for releases.  ## Parameters  - `version`: The version of the release.  ## Returns  Returns a `Json<SoftwareVersionResponse>` object containing the version of the release.
     * @summary Simulate GitHub API for releases
     * @param {string} version 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public async softwareReleasesTag(version: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<SoftwareVersionResponse>> {
        return SoftwareApiFp(this.configuration).softwareReleasesTag(version, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * This function is an API endpoint that retrieves the version of the server. It is tagged with \"software\" for OpenAPI documentation.  ## Returns  If successful, this function returns a `Json<SoftwareVersionResponse>` object containing the version of the server.
     * @summary Retrieve the server version
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SoftwareApi
     */
    public async softwareVersion(options?: AxiosRequestConfig) : Promise<AxiosResponse<SoftwareVersionResponse>> {
        return SoftwareApiFp(this.configuration).softwareVersion(options).then((request) => request(this.axios, this.basePath));
    }
}
