/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Strategy } from '../models';
import { StrategySummary } from '../models';
import { UpdateStrategyRequest } from '../models';
/**
 * StrategyApi - axios parameter creator
 * @export
 */
export const StrategyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Pro-compatible (`strategies.py list`). Only the \"Default\" strategy exists: it is the policy every device receives.
         * @summary List strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        strategies: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/strategies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Pro-compatible (`strategies.py view`). `options` holds the managed settings (a missing key is not managed, `\"\"` resets it to the device default); `keys` lists every setting a policy may manage.
         * @summary Get a strategy
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        strategyGet: async (guid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'guid' is not null or undefined
            if (guid === null || guid === undefined) {
                throw new RequiredError('guid','Required parameter guid was null or undefined when calling strategyGet.');
            }
            const localVarPath = `/api/strategies/{guid}`
                .replace(`{${"guid"}}`, encodeURIComponent(String(guid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Not in Pro's published API. Every device receives the strategy again on its next heartbeat, which reverts local changes to managed settings.
         * @summary Re-push a strategy
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        strategyRepush: async (guid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'guid' is not null or undefined
            if (guid === null || guid === undefined) {
                throw new RequiredError('guid','Required parameter guid was null or undefined when calling strategyRepush.');
            }
            const localVarPath = `/api/strategies/{guid}/repush`
                .replace(`{${"guid"}}`, encodeURIComponent(String(guid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Not in Pro's published API. Replaces the managed settings; devices receive them on their next heartbeat. 400 names the first invalid setting; nothing is saved then.
         * @summary Update a strategy's options
         * @param {UpdateStrategyRequest} body 
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        strategyUpdate: async (body: UpdateStrategyRequest, guid: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling strategyUpdate.');
            }
            // verify required parameter 'guid' is not null or undefined
            if (guid === null || guid === undefined) {
                throw new RequiredError('guid','Required parameter guid was null or undefined when calling strategyUpdate.');
            }
            const localVarPath = `/api/strategies/{guid}`
                .replace(`{${"guid"}}`, encodeURIComponent(String(guid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication authorization_admin required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StrategyApi - functional programming interface
 * @export
 */
export const StrategyApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Pro-compatible (`strategies.py list`). Only the \"Default\" strategy exists: it is the policy every device receives.
         * @summary List strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategies(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<StrategySummary>>>> {
            const localVarAxiosArgs = await StrategyApiAxiosParamCreator(configuration).strategies(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Pro-compatible (`strategies.py view`). `options` holds the managed settings (a missing key is not managed, `\"\"` resets it to the device default); `keys` lists every setting a policy may manage.
         * @summary Get a strategy
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategyGet(guid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Strategy>>> {
            const localVarAxiosArgs = await StrategyApiAxiosParamCreator(configuration).strategyGet(guid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Not in Pro's published API. Every device receives the strategy again on its next heartbeat, which reverts local changes to managed settings.
         * @summary Re-push a strategy
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategyRepush(guid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Strategy>>> {
            const localVarAxiosArgs = await StrategyApiAxiosParamCreator(configuration).strategyRepush(guid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Not in Pro's published API. Replaces the managed settings; devices receive them on their next heartbeat. 400 names the first invalid setting; nothing is saved then.
         * @summary Update a strategy's options
         * @param {UpdateStrategyRequest} body 
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategyUpdate(body: UpdateStrategyRequest, guid: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Strategy>>> {
            const localVarAxiosArgs = await StrategyApiAxiosParamCreator(configuration).strategyUpdate(body, guid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * StrategyApi - factory interface
 * @export
 */
export const StrategyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Pro-compatible (`strategies.py list`). Only the \"Default\" strategy exists: it is the policy every device receives.
         * @summary List strategies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategies(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<StrategySummary>>> {
            return StrategyApiFp(configuration).strategies(options).then((request) => request(axios, basePath));
        },
        /**
         * Pro-compatible (`strategies.py view`). `options` holds the managed settings (a missing key is not managed, `\"\"` resets it to the device default); `keys` lists every setting a policy may manage.
         * @summary Get a strategy
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategyGet(guid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Strategy>> {
            return StrategyApiFp(configuration).strategyGet(guid, options).then((request) => request(axios, basePath));
        },
        /**
         * Not in Pro's published API. Every device receives the strategy again on its next heartbeat, which reverts local changes to managed settings.
         * @summary Re-push a strategy
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategyRepush(guid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Strategy>> {
            return StrategyApiFp(configuration).strategyRepush(guid, options).then((request) => request(axios, basePath));
        },
        /**
         * Not in Pro's published API. Replaces the managed settings; devices receive them on their next heartbeat. 400 names the first invalid setting; nothing is saved then.
         * @summary Update a strategy's options
         * @param {UpdateStrategyRequest} body 
         * @param {string} guid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async strategyUpdate(body: UpdateStrategyRequest, guid: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Strategy>> {
            return StrategyApiFp(configuration).strategyUpdate(body, guid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StrategyApi - object-oriented interface
 * @export
 * @class StrategyApi
 * @extends {BaseAPI}
 */
export class StrategyApi extends BaseAPI {
    /**
     * Pro-compatible (`strategies.py list`). Only the \"Default\" strategy exists: it is the policy every device receives.
     * @summary List strategies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StrategyApi
     */
    public async strategies(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<StrategySummary>>> {
        return StrategyApiFp(this.configuration).strategies(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Pro-compatible (`strategies.py view`). `options` holds the managed settings (a missing key is not managed, `\"\"` resets it to the device default); `keys` lists every setting a policy may manage.
     * @summary Get a strategy
     * @param {string} guid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StrategyApi
     */
    public async strategyGet(guid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Strategy>> {
        return StrategyApiFp(this.configuration).strategyGet(guid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Not in Pro's published API. Every device receives the strategy again on its next heartbeat, which reverts local changes to managed settings.
     * @summary Re-push a strategy
     * @param {string} guid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StrategyApi
     */
    public async strategyRepush(guid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Strategy>> {
        return StrategyApiFp(this.configuration).strategyRepush(guid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Not in Pro's published API. Replaces the managed settings; devices receive them on their next heartbeat. 400 names the first invalid setting; nothing is saved then.
     * @summary Update a strategy's options
     * @param {UpdateStrategyRequest} body 
     * @param {string} guid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StrategyApi
     */
    public async strategyUpdate(body: UpdateStrategyRequest, guid: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Strategy>> {
        return StrategyApiFp(this.configuration).strategyUpdate(body, guid, options).then((request) => request(this.axios, this.basePath));
    }
}
