/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AbSettingsResponse
 */
export interface AbSettingsResponse {

    /**
     * @type {string}
     * @memberof AbSettingsResponse
     */
    error?: string | null;

    /**
     * @type {number}
     * @memberof AbSettingsResponse
     */
    max_peer_one_ab: number;
}
