/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuditAlarmRequest
 */
export interface AuditAlarmRequest {

    /**
     * @type {string}
     * @memberof AuditAlarmRequest
     */
    id?: string;

    /**
     * @type {string}
     * @memberof AuditAlarmRequest
     */
    uuid?: string;

    /**
     * @type {number}
     * @memberof AuditAlarmRequest
     */
    typ?: number;

    /**
     * @type {string}
     * @memberof AuditAlarmRequest
     */
    info?: string;

    /**
     * @type {number}
     * @memberof AuditAlarmRequest
     */
    conn_id?: number;

    /**
     * @type {string}
     * @memberof AuditAlarmRequest
     */
    nonce?: string;

    /**
     * @type {string}
     * @memberof AuditAlarmRequest
     */
    conn_audit_ref?: string | null;
}
