/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * `GET /api/audits/login` row: one OIDC login and how it ended.
 *
 * @export
 * @interface AuditLoginLog
 */
export interface AuditLoginLog {

    /**
     * @type {string}
     * @memberof AuditLoginLog
     */
    guid: string;

    /**
     * @type {number}
     * @memberof AuditLoginLog
     */
    created_at: number;

    /**
     * `ok`, `idp_denied`, `idp_error`, `inactive` or `refused`.
     *
     * @type {string}
     * @memberof AuditLoginLog
     */
    outcome: string;

    /**
     * @type {string}
     * @memberof AuditLoginLog
     */
    detail: string;

    /**
     * `native`, `web` or `console`.
     *
     * @type {string}
     * @memberof AuditLoginLog
     */
    client: string;

    /**
     * @type {string}
     * @memberof AuditLoginLog
     */
    user: string;

    /**
     * Self-reported by the client when it started the login.
     *
     * @type {string}
     * @memberof AuditLoginLog
     */
    rustdesk_id: string;

    /**
     * @type {string}
     * @memberof AuditLoginLog
     */
    hostname: string;

    /**
     * @type {string}
     * @memberof AuditLoginLog
     */
    os: string;

    /**
     * @type {string}
     * @memberof AuditLoginLog
     */
    ip: string;
}
