/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * `PUT /api/audit` body (spec §8): end-of-session note by GUID.
 *
 * @export
 * @interface AuditNoteRequest
 */
export interface AuditNoteRequest {

    /**
     * @type {string}
     * @memberof AuditNoteRequest
     */
    guid: string;

    /**
     * @type {string}
     * @memberof AuditNoteRequest
     */
    note?: string;
}
