/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AuditConnLog } from './audit-conn-log';
 /**
 * 
 *
 * @export
 * @interface AuditPageForAuditConnLog
 */
export interface AuditPageForAuditConnLog {

    /**
     * @type {number}
     * @memberof AuditPageForAuditConnLog
     */
    total: number;

    /**
     * @type {Array<AuditConnLog>}
     * @memberof AuditPageForAuditConnLog
     */
    data: Array<AuditConnLog>;
}
