/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AuditLoginLog } from './audit-login-log';
 /**
 * 
 *
 * @export
 * @interface AuditPageForAuditLoginLog
 */
export interface AuditPageForAuditLoginLog {

    /**
     * @type {number}
     * @memberof AuditPageForAuditLoginLog
     */
    total: number;

    /**
     * @type {Array<AuditLoginLog>}
     * @memberof AuditPageForAuditLoginLog
     */
    data: Array<AuditLoginLog>;
}
