/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuditConnRequest
 */
export interface AuditConnRequest {

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    id?: string;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    uuid?: string;

    /**
     * @type {number}
     * @memberof AuditConnRequest
     */
    conn_id?: number;

    /**
     * @type {number}
     * @memberof AuditConnRequest
     */
    session_id?: number;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    nonce?: string;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    ip?: string;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    action?: string;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    os_login?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    conn_audit_ref?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnRequest
     */
    note?: string | null;
}
