/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AuditAlarmLog } from './audit-alarm-log';
 /**
 * 
 *
 * @export
 * @interface AuditPageForAuditAlarmLog
 */
export interface AuditPageForAuditAlarmLog {

    /**
     * @type {number}
     * @memberof AuditPageForAuditAlarmLog
     */
    total: number;

    /**
     * @type {Array<AuditAlarmLog>}
     * @memberof AuditPageForAuditAlarmLog
     */
    data: Array<AuditAlarmLog>;
}
