/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * `GET /api/audits/conn` row (audit-api-spec.md §9.2).
 *
 * @export
 * @interface AuditConnLog
 */
export interface AuditConnLog {

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    guid: string;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    remote: string;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    remote_name?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    peer_id?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    peer_name?: string | null;

    /**
     * Viewer machine from the session user's latest login on that viewer ID (self-reported).
     * @type {string}
     * @memberof AuditConnLog
     */
    peer_hostname?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    peer_os?: string | null;

    /**
     * Client address of that login; the session's own address is `ip`.
     * @type {string}
     * @memberof AuditConnLog
     */
    peer_login_ip?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    user?: string | null;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    ip?: string | null;

    /**
     * @type {number}
     * @memberof AuditConnLog
     */
    conn_type?: number | null;

    /**
     * @type {number}
     * @memberof AuditConnLog
     */
    primary_auth?: number | null;

    /**
     * @type {number}
     * @memberof AuditConnLog
     */
    two_factor?: number | null;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    session_id?: string | null;

    /**
     * @type {number}
     * @memberof AuditConnLog
     */
    conn_id?: number | null;

    /**
     * @type {number}
     * @memberof AuditConnLog
     */
    created_at: number;

    /**
     * @type {number}
     * @memberof AuditConnLog
     */
    end_time?: number | null;

    /**
     * @type {string}
     * @memberof AuditConnLog
     */
    note?: string | null;

    /**
     * @type {boolean}
     * @memberof AuditConnLog
     */
    active: boolean;
}
