/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * `GET /api/audits/file` row (audit-api-spec.md §9.2).
 *
 * @export
 * @interface AuditFileLog
 */
export interface AuditFileLog {

    /**
     * @type {string}
     * @memberof AuditFileLog
     */
    guid: string;

    /**
     * @type {string}
     * @memberof AuditFileLog
     */
    remote: string;

    /**
     * @type {string}
     * @memberof AuditFileLog
     */
    peer_id?: string | null;

    /**
     * @type {string}
     * @memberof AuditFileLog
     */
    user?: string | null;

    /**
     * @type {number}
     * @memberof AuditFileLog
     */
    type: number;

    /**
     * @type {string}
     * @memberof AuditFileLog
     */
    path: string;

    /**
     * @type {boolean}
     * @memberof AuditFileLog
     */
    is_file: boolean;

    /**
     * @type {number}
     * @memberof AuditFileLog
     */
    num?: number | null;

    /**
     * @type {any}
     * @memberof AuditFileLog
     */
    files?: any | null;

    /**
     * @type {string}
     * @memberof AuditFileLog
     */
    ip?: string | null;

    /**
     * @type {number}
     * @memberof AuditFileLog
     */
    created_at: number;
}
