/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuditFileRequest
 */
export interface AuditFileRequest {

    /**
     * @type {string}
     * @memberof AuditFileRequest
     */
    id?: string;

    /**
     * @type {string}
     * @memberof AuditFileRequest
     */
    uuid?: string;

    /**
     * @type {string}
     * @memberof AuditFileRequest
     */
    peer_id?: string;

    /**
     * @type {number}
     * @memberof AuditFileRequest
     */
    conn_id?: number;

    /**
     * @type {number}
     * @memberof AuditFileRequest
     */
    type?: number;

    /**
     * @type {string}
     * @memberof AuditFileRequest
     */
    path?: string;

    /**
     * @type {boolean}
     * @memberof AuditFileRequest
     */
    is_file?: boolean;

    /**
     * @type {string}
     * @memberof AuditFileRequest
     */
    info?: string;

    /**
     * @type {string}
     * @memberof AuditFileRequest
     */
    nonce?: string;
}
