/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AuditFileLog } from './audit-file-log';
 /**
 * 
 *
 * @export
 * @interface AuditPageForAuditFileLog
 */
export interface AuditPageForAuditFileLog {

    /**
     * @type {number}
     * @memberof AuditPageForAuditFileLog
     */
    total: number;

    /**
     * @type {Array<AuditFileLog>}
     * @memberof AuditPageForAuditFileLog
     */
    data: Array<AuditFileLog>;
}
