/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * `GET /api/audits/console` row (audit-api-spec.md §9.2). Nothing writes `audit_console` yet.
 *
 * @export
 * @interface AuditConsoleLog
 */
export interface AuditConsoleLog {

    /**
     * @type {string}
     * @memberof AuditConsoleLog
     */
    guid: string;

    /**
     * @type {number}
     * @memberof AuditConsoleLog
     */
    typ: number;

    /**
     * @type {number}
     * @memberof AuditConsoleLog
     */
    iop: number;

    /**
     * @type {string}
     * @memberof AuditConsoleLog
     */
    operator?: string | null;

    /**
     * @type {any}
     * @memberof AuditConsoleLog
     */
    info: any;

    /**
     * @type {number}
     * @memberof AuditConsoleLog
     */
    created_at: number;
}
