/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { StrategyPush } from './strategy-push';
 /**
 * Reply to `/api/heartbeat`; the client applies `strategy` when present (`hbbs_http/sync.rs`).
 *
 * @export
 * @interface HeartbeatResponse
 */
export interface HeartbeatResponse {

    /**
     * @type {number}
     * @memberof HeartbeatResponse
     */
    modified_at: number;

    /**
     * @type {StrategyPush}
     * @memberof HeartbeatResponse
     */
    strategy?: StrategyPush | null;
}
