/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LoginRequest
 */
export interface LoginRequest {

    /**
     * @type {string}
     * @memberof LoginRequest
     */
    username: string;

    /**
     * @type {string}
     * @memberof LoginRequest
     */
    password: string;

    /**
     * @type {string}
     * @memberof LoginRequest
     */
    id: string;

    /**
     * @type {string}
     * @memberof LoginRequest
     */
    uuid: string;
}
