/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * One setting the device policy can manage.
 *
 * @export
 * @interface PolicyKeyInfo
 */
export interface PolicyKeyInfo {

    /**
     * @type {string}
     * @memberof PolicyKeyInfo
     */
    key: string;

    /**
     * @type {string}
     * @memberof PolicyKeyInfo
     */
    label: string;

    /**
     * @type {Array<string>}
     * @memberof PolicyKeyInfo
     */
    values: Array<string>;
}
