/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PolicyKeyInfo } from './policy-key-info';
 /**
 * A strategy with its managed options. A key missing from `options` is not managed; `\"\"` resets it to the device's default.
 *
 * @export
 * @interface Strategy
 */
export interface Strategy {

    /**
     * @type {string}
     * @memberof Strategy
     */
    guid: string;

    /**
     * @type {string}
     * @memberof Strategy
     */
    name: string;

    /**
     * @type {number}
     * @memberof Strategy
     */
    modified_at: number;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof Strategy
     */
    options: { [key: string]: string; };

    /**
     * The settings a policy may manage, for the webconsole.
     *
     * @type {Array<PolicyKeyInfo>}
     * @memberof Strategy
     */
    keys: Array<PolicyKeyInfo>;
}
