/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * A strategy in `GET /api/strategies` (Pro's `strategies.py list` reads `guid` and `name`).
 *
 * @export
 * @interface StrategySummary
 */
export interface StrategySummary {

    /**
     * @type {string}
     * @memberof StrategySummary
     */
    guid: string;

    /**
     * @type {string}
     * @memberof StrategySummary
     */
    name: string;

    /**
     * Epoch milliseconds; devices report the value they last received.
     *
     * @type {number}
     * @memberof StrategySummary
     */
    modified_at: number;
}
