/* tslint:disable */
/* eslint-disable */
/**
 * rustdesk-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UsersResponse
 */
export interface UsersResponse {

    /**
     * @type {string}
     * @memberof UsersResponse
     */
    msg: string;

    /**
     * @type {number}
     * @memberof UsersResponse
     */
    total: number;

    /**
     * @type {string}
     * @memberof UsersResponse
     */
    data: string;
}
